Add documentation on downloading an alternative certificate
unixcharles/acme-client pull request #192
Opened 2020-09-16 21:08 UTC by chrisUsick

Added some basic documentation with the  primary goal of demonstrating how to invoke `Order#certificate` with the `preferred_chain` keyword argument as per [this comment](https://github.com/unixcharles/acme-client/pull/190#issuecomment-692731843)

2020-09-16 22:05 UTC, gschorkopf requested changes

2020-09-16 22:05 UTC, gschorkopf commented on README.md
> +Note: if the specified peferred chain doesn't match an existing alternative certificate it will return `nil`.
Typo

```suggestion
Note: if the specified preferred chain doesn't match an existing alternative certificate it will return `nil`.
```

2020-09-16 22:05 UTC, gschorkopf commented on README.md
> +Note: if the specified peferred chain doesn't match an existing alternative certificate it will return `nil`.
I think the current implementation is actually going to raise an error, and is depending on the consumer of the gem to catch `Acme::Client::Error::PreferredChainNotMatched`. Correct me if I'm wrong.

See https://github.com/unixcharles/acme-client/pull/190/files#diff-e843384610a1a0cb8c21582bbed52188R151

2020-09-17 15:43 UTC, chrisUsick commented
Ah, you're right regarding the raising of the exception. Updated accordingly.

2020-09-18 18:16 UTC, closed without merging

2020-09-18 18:42 UTC, unixcharles commented
I'm not too sure why but github auto closed this one when I merged other PR. I'll cherry pick the changes.

2020-09-18 19:12 UTC, chrisUsick commented
Okay, thanks!